src/articulosTablon/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='inicio'),
    path('ciudad/<slug:ciudad>', views.ListaCiudad.as_view(), name='ciudadSr'),
    path('categoria/<slug:categoria>', views.ListaCategoria.as_view(), name='categoriaSr'),
    path('usuario/', views.ListaUsuario.as_view(), name='ususarioSrArg'),
    path('usuario/<int:pk>', views.ListaUsuario.as_view(), name='ususarioSrArg'),
    path('ficha/<slug:slug>', views.DetalleArticulo.as_view(), name='ficha'),
    path('crear/', views.CrearArticulo.as_view(), name='crear'),
    path('actualizar/<int:pk>', views.ActualizarArticulo.as_view(), name='actualizar'),
    path('borrar/<int:pk>', views.BorrarArticulo.as_view(), name='borrar'),
]

src/tablonOnline/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings

urlpatterns = [
    path('', include('articulosTablon.urls')),
    path('generico/', include('paginasSitio.urls')),
    path('profile/', include('userExtend.urls')),
    path('cuenta/', include('allauth.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/tonline/urls.py
from django.urls import path
from django.conf.urls import include, url
from . import views

app_name = 'tonline'

urlpatterns = [
    # path('', views.Index.as_view(), name='index'),
    path('', views.index, name='index'),
    path('ciudad/<int:ciudad>', views.ListaCiudad.as_view(), name='listaCiudad'),
    path('lc/<int:categoria>', views.ListaCategoria.as_view(), name='lista'),
    path('lu/', views.ListaUsiario.as_view(), name='listausr'),
    path('d/<int:pk>', views.DetalleT.as_view(), name='detalle'),  # Por Id
    path('c/', views.CrearT.as_view(), name='crear'),
    path('u/<int:pk>', views.actualizarT.as_view(), name='actualizar'),
    path('b/<int:pk>', views.BorrarT.as_view(), name='borrar'),
    path('<slug>', views.DetalleT.as_view(), name='detallee'),  # por Slug
    # path('signup/', views.signup, name='signup'),
    # url(r'^(?P<slug>[-_\w]+)/$', views.DetalleT.as_view(), name='detallee'),#por Slug
]

src/articulosTablon/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from ckeditor.fields import RichTextField

class Categoria(models.Model):
    nombre = models.CharField(max_length=20, verbose_name='Categoria')
    slug = models.SlugField(null=True, blank=True)

    def __str__(self):
        return self.nombre


def categoria_pre_save_receptor(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.nombre)


pre_save.connect(categoria_pre_save_receptor, sender=Categoria)


class Scategoria(models.Model):
    nombre = models.CharField(max_length=20, verbose_name='Subcategoria')
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, null=False, verbose_name='Categoria')
    slug = models.SlugField(null=True, blank=True)

    class Meta:
        verbose_name = 'Sub categoria'
        verbose_name_plural = 'Sub categorias'

    def __str__(self):
        return self.nombre


def scategoria_pre_save_receptor(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.nombre)


pre_save.connect(scategoria_pre_save_receptor, sender=Scategoria)


class Ciudad(models.Model):
    nombre = models.CharField(max_length=20, verbose_name='Ciudad')
    slug = models.SlugField(null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Ciudades'

    def __str__(self):
        return self.nombre


def ciudad_pre_save_receptor(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.nombre)


pre_save.connect(ciudad_pre_save_receptor, sender=Ciudad)


class ArticuloModelManager(models.Manager):
    def srCategoria(self, categoria):
        return super(ArticuloModelManager, self).filter(categoria__slug=categoria)

    def srUser(self, usr):
        return super(ArticuloModelManager, self).filter(creado=usr)

    def srUserArg(self, usr):
        return super(ArticuloModelManager, self).filter(creado=usr)

    def srCiudad(self, ciudad):
        return super(ArticuloModelManager, self).filter(ciudad__slug=ciudad)


class Articulo(models.Model):
    TYPE_ADD = (
        ('pa', 'Particular'),
        ('pr', 'Privado'),
    )

    categoria = models.ForeignKey(Scategoria, on_delete=models.CASCADE, null=False, verbose_name='Categoria')
    nombre = models.CharField(max_length=150, verbose_name='Descripción corta')
    #descripcion = models.TextField(max_length=500, verbose_name='Descripcion')
    descripcion = RichTextField(verbose_name='Descripcion')
    fechaC = models.DateTimeField(auto_now_add=True, verbose_name='Fecha creacion')
    fechaM = models.DateTimeField(auto_now=True, verbose_name='Fecha modificacion')
    tipo = models.CharField(max_length=2, choices=TYPE_ADD, verbose_name='Tipo de vendedor')
    ciudad = models.ForeignKey(Ciudad, on_delete=models.CASCADE, null=False, verbose_name='Ciudad')
    precio = models.FloatField(verbose_name='Precio')
    visitas = models.IntegerField(verbose_name='Nº Visitas', default=0)
    visible = models.BooleanField(verbose_name='Publicado', default=True)
    creado = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    slug = models.SlugField(null=True, blank=True)

    objects = ArticuloModelManager()

    class Meta:
        ordering = ['-fechaM', '-fechaC']

    def __str__(self):
        return self.nombre

    def get_absolute_url(self):
        return "/ficha/%s" % (self.slug)


def articulo_pre_save_receptor(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.nombre)


pre_save.connect(articulo_pre_save_receptor, sender=Articulo)


class File(models.Model):
    articulo = models.ForeignKey(Articulo, on_delete=models.CASCADE)
    imagenes = models.ImageField(upload_to='static')

src/articulosTablon/forms.py
from django import forms
from django.forms import inlineformset_factory
from ckeditor.widgets import CKEditorWidget

from .models import Articulo, File


class ArticuloForm(forms.ModelForm):
    class Meta:
        model = Articulo
        descripcion = forms.CharField(widget=CKEditorWidget())
        exclude = ("slug", "fechaC", "visitas", "fechaM")


class FileForm(forms.ModelForm):
    class Meta:
        model = File
        exclude = ()


FileInlineFormSet = inlineformset_factory(Articulo, File,
                                          form=FileForm, extra=1)

src/articulosTablon/views.py
from django.db import transaction
from django.http import Http404, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Ciudad, Scategoria, Articulo
from.forms import ArticuloForm, FileForm, FileInlineFormSet

def index(request):
    template = "index.html"
    queryset1 = Scategoria.objects.all()
    queryset2 = Ciudad.objects.all()
    context = {
        "ciudades": queryset2,
        "scategoria_list": queryset1,
    }
    return render(request, template, context)


class ListaCiudad(ListView):
    model = Articulo
    template_name = "articulosTablon/articulo_list.html"

    def get_queryset(self):
        return Articulo.objects.srCiudad(self.kwargs['ciudad'])


class ListaCategoria(ListView):
    model = Articulo
    template_name = "articulosTablon/articulo_list.html"

    def get_queryset(self):
        return Articulo.objects.srCategoria(self.kwargs['categoria'])


class ListaUsuario (ListView):
    model = Articulo
    template_name = "articulosTablon/articulo_list.html"

    def get_queryset(self):
        if 'pk' in self.kwargs:
            return Articulo.objects.srUserArg(self.kwargs['pk'])
        elif not self.request.user.is_authenticated:
            pass
        else:
            return Articulo.objects.srUser(self.request.user)


class DetalleArticulo(DetailView):
    model = Articulo

    def dispatch(self, request, *args, **kwargs):
        #Articulo1 = 
        Articulo.objects.filter(slug=self.kwargs['slug']).update(visitas = self.get_object().visitas +1)  # Por id -->(id=self.kwargs['pk'])
        #Articulo1.visitas += 1
        #Articulo1.save(force_update=True, update_fields=['visitas'])
        return super().dispatch(request, *args, **kwargs)

class CrearArticulo(LoginRequiredMixin, CreateView):
    model = Articulo
    fields = ["nombre", "descripcion", "categoria", "tipo", "ciudad", "precio", "visible"]

    def get_context_data(self, **kwargs):
        data = super(CrearArticulo, self).get_context_data(**kwargs)
        if self.request.POST:
            data['file'] = FileInlineFormSet(self.request.POST, self.request.FILES)
        else:
            data['file'] = FileInlineFormSet()
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        file = context['file']
        with transaction.atomic():
            self.object = form.save()
            self.object.creado = self.request.user
            if file.is_valid():
                file.instance = self.object
        return super(CrearArticulo, self).form_valid(form)


class ActualizarArticulo(LoginRequiredMixin, UpdateView):
    model = Articulo
    fields = ["nombre", "descripcion", "categoria", "tipo", "ciudad", "precio", "visible"]

    def dispatch(self, request, *args, **kwargs):
        Articulo1 = Articulo.objects.get(id=self.kwargs['pk'])
        if Articulo1.creado.id == self.request.user.id:
            return super().dispatch(request, *args, **kwargs)
        else:
            return redirect(reverse_lazy('inicio'))

    def get_context_data(self, **kwargs):
        data = super(ActualizarArticulo, self).get_context_data(**kwargs)
        if self.request.POST:
            data['file'] = FileInlineFormSet(self.request.POST, self.request.FILES, instance=self.object)
        else:
            data['file'] = FileInlineFormSet(instance=self.object)
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        file = context['file']
        with transaction.atomic():
            self.object = form.save()

            if file.is_valid():
                file.instance = self.object
                file.save()
        return super(ActualizarArticulo, self).form_valid(form)


class BorrarArticulo(LoginRequiredMixin, DeleteView):
    model = Articulo

    def dispatch(self, request, *args, **kwargs):
        Articulo1 = Articulo.objects.get(id=self.kwargs['pk'])
        if Articulo1.creado.id == self.request.user.id:
            return super().dispatch(request, *args, **kwargs)
        else:
            return redirect(reverse_lazy('inicio'))

    def get_success_url(self):
        return redirect(reverse_lazy('ususarioSr'))

src/templates/articulosTablon/articulo_confirm_delete.html
{% extends "base.html" %}

{% block head_title %}
   Esta seguro!!
{% endblock %}

{% block section %}
<h3>Esta seguro de querer borrar el articulo {{object.nombre}}</h3>
<br>
{% if object.imagen %}
<img src="{{object.imagen.url}}" alt="img" class="img-responsive img-rounded">
{% endif %}
<form method="POST" action="">
{% csrf_token %}
<input type="submit" class="primaryAction btn btn-danger" value="Confirmar">
<a class="primaryAction btn btn-primary" href="{{ object.get_absolute_url }}">Cancelar</a>
</form>
{% endblock %}

src/templates/articulosTablon/articulo_detail.html
{% extends "base.html" %}

{% block head_title %}
    Articulo | {{object.nombre}}
{% endblock %}


{% block section %}

    <div class="fichaS">
    <p><span class = 'nombreF'>{{object.nombre}}</span> | <span class = 'precioF'> Precio: {{object.precio}}€</span> | <span class = 'PublicadoF'> Actualizado: {{ object.fechaM|timesince }}</span></p>
        <p><span class = 'referenciaF'>Ref:{{object.id}} </span>|<span class = 'tipoF'> Tipo de vendedor: {{object.get_tipo_display}}</span> |<span class = 'fechaF'> Fecha de publicacion: {{object.fechaM|date:"D d M Y" }}</span></p>
        <span class = 'descripcionF'><p><u>Descripcion:</u>{{object.descripcion|safe}}</p></span><br><hr>
    <p>Veces visto:{{object.visitas}}</p>
    {% if object.file_set.all %}
    <ul id="carousel"><span id="cargando">Cargando imágenes...</span>
        {%for img in object.file_set.all%}
            <li class="noselected"><img src="{{img.imagenes.url}}" alt="{{object.nombre}}" class="img_list img-responsive img-rounded"></li>
        {%endfor%}
    </ul>
    {% endif %}
    </div><br/>
<script>
        document.getElementById('cargando').className = 'noselected';
        var indice = 0;
        var elemento = document.getElementById('carousel').getElementsByTagName('li');
        slideshow();
 </script>
{% endblock %}

src/templates/articulosTablon/articulo_form.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
    <h2>Añadir anuncio</h2>
    <hr>
    <div class="col-md-4">
        <form action="" method="POST" enctype="multipart/form-data"> {% csrf_token %}
            <table>
            {{ form.as_table }}
            </table>
            <table class="table">
                {{ file.management_form }}

                {% for form in file.forms %}
                    {% if forloop.first %}
                        <thead>
                        <tr>
                            {% for field in form.visible_fields %}
                                <th>{{ field.label|capfirst }}</th>
                            {% endfor %}
                        </tr>
                        </thead>
                    {% endif %}
                    <tr class="{% cycle row1 row2 %} formset_row">
                        {% for field in form.visible_fields %}
                            <td>
                                {% if forloop.first %}
                                    {% for hidden in form.hidden_fields %}
                                        {{ hidden }}
                                    {% endfor %}
                                {% endif %}
                                {{ field.errors.as_ul }}
                                {{ field }}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
            <input class="btn btn-primary" type="submit" value="Guardar"/> <a class="btn btn-primary "href="/">Atras</a>
        </form>
    </div>
    <script src="{% static 'formset/jquery.formset.js' %}"></script>
    <script type="text/javascript">
        $('.formset_row').formset({
            addText: 'Añadir otra imagen',
            deleteText: 'Borrar',
            prefix: 'file_set'
        });
    </script>
{% endblock %}

src/templates/articulosTablon/articulo_list.html
{% extends "base.html" %}

{% block head_title %}
Lista de articulos
{% endblock %}

{% block section %}
{% for art in articulo_list %}
<div class="articulo_class">
    <div class='tituloArtList'>
        <p><u>{{art.nombre}}</u> ubicado en {{art.ciudad}} </p>
    </div>
    <div class='decripcionArtList'>
        <p><b>Descripcion:</b> {{art.descripcion|safe}}</p><br>
        <hr>
    </div>
    <p class='decripcionArtList'>
    <p><b>Precio:</b> {{art.precio }}€ | <b>Tipo de vendedor:</b> {{art.get_tipo_display }}</p>
    {% if art.fechaC|date:"D d M Y" == art.fechaM|date:"D d M Y" %}
    <p>Fecha de publicacion: {{art.fechaC|date:"D d M Y" }}</p>
    {% else %}
    <p>Fecha de publicacion: {{art.fechaC|date:"D d M Y" }} | Fecha de modificación: {{art.fechaM|date:"D d M Y" }}</p>
    {% endif %}
    <p>Publicado hace: {{ art.fechaC|timesince }}</p>
    <div class="Options">
        <a href="{% url 'ficha' art.slug %}">Ver articulo</a>
        {% if user.is_authenticated and user.id == art.creado.id %}
        <a href="{% url 'actualizar' art.id %}">Modificar</a>
        <a href="{% url 'borrar' art.id %}">Borrar </a>
        <p> | Eres el propietario del anuncio</p>
        {% else %}
        <p> Anuncio Publicado por <a href="{% url 'perfilDetalle' art.creado %}">{{art.creado}}</a></p>
        {% endif %}
    </div>
</div>
<br/>

{% empty %}
<p>No hay articulos en esta categotia</p>
{% endfor %}
{% endblock %}